In [1]:
import pandas as pd
import numpy as np
import chardet
import ast

In [2]:
with open("dataset.csv", "rb") as f:
    result = chardet.detect(f.read(100_000))

result

df = pd.read_csv("dataset.csv", encoding=result["encoding"], sep=";")
df.head()

,Name,Author,Date,Rating Value,Rating Count,Preparation Time,Cooking Time,Category,Cuisine,Ingredients,Ingredients_Raw,Instructions,Cooking Methods,Implements,Number of steps,Servings,Nutrition,URL
0,Pineapple Glaze for Ham,Jackie,01/04/2025,4.5,104.0,10.0,5.0,['Dinner'],['American'],"[{'ingredient': 'pineapple', 'quantity': '1', ...","['1 (15.25 ounce) can sliced pineapple, draine...","['Gather the ingredients.', 'Before baking ham...",['microwave'],['microwave'],4.0,"['14', '3 cups']","{'Calories': '93 kcal', 'Carbohydrates': '24 g...",https://www.allrecipes.com/recipe/17116/pineap...
1,Awesome Egg Rolls,ROUVER,01/04/2025,4.5,299.0,35.0,15.0,"['Dinner', 'Appetizer']","['World', 'Asian']","[{'ingredient': 'vegetable oil', 'quantity': '...","['1 tsp vegetable oil', '1 egg, beaten', '6 cu...","['Gather all ingredients.', 'Mix cabbage, bean...",['fry'],"['skillet', 'cutting board']",11.0,"['10', '20 egg rolls']","{'Calories': '1268 kcal', 'Carbohydrates': '57...",https://www.allrecipes.com/recipe/84099/awesom...
2,Spanish Tortilla,Leslie Rosas,01/04/2025,4.3,15.0,10.0,10.0,['Breakfast'],['Spanish'],"[{'ingredient': 'olive oil', 'quantity': '0.25...","['0.25 cup olive oil', '2 potatoes, peeled', '...",['Slice edges off of potatoes so that potatoes...,['fry'],['skillet'],3.0,4,"{'Calories': '447 kcal', 'Carbohydrates': '22 ...",https://www.allrecipes.com/recipe/24342/spanis...
3,Spicy Tarragon Yogurt Chicken,John Mitzewich,01/04/2025,4.5,42.0,10.0,15.0,['Dinner'],['American'],"[{'ingredient': 'tarragon sprigs', 'quantity':...","['1 bunch fresh tarragon sprigs, leaves only',...",['Set 4 tarragon sprigs aside strip leaves fr...,['grill'],"['grill', 'thermometer', 'blender']",5.0,6,"{'Calories': '316 kcal', 'Carbohydrates': '3 g...",https://www.allrecipes.com/recipe/223045/spicy...
4,Apple Bread,karla,01/04/2025,4.7,435.0,15.0,45.0,['Brunch'],['American'],"[{'ingredient': 'spray', 'quantity': '', 'unit...","['cooking spray', '3 cups all-purpose flour', ...",['Preheat the oven to 300 degrees F (150 degre...,['bake'],"['pan', 'oven', 'whisk']",3.0,"['16', '2 (8x4-inch) loaves']","{'Calories': '377 kcal', 'Carbohydrates': '47 ...",https://www.allrecipes.com/recipe/223602/apple...

In [3]:
df = df.drop(labels=["Author", "Date", "Number of steps", "URL", "Ingredients", "Rating Count"], axis=1)
df

,Name,Rating Value,Preparation Time,Cooking Time,Category,Cuisine,Ingredients_Raw,Instructions,Cooking Methods,Implements,Servings,Nutrition
0,Pineapple Glaze for Ham,4.5,10.0,5.0,['Dinner'],['American'],"['1 (15.25 ounce) can sliced pineapple, draine...","['Gather the ingredients.', 'Before baking ham...",['microwave'],['microwave'],"['14', '3 cups']","{'Calories': '93 kcal', 'Carbohydrates': '24 g..."
1,Awesome Egg Rolls,4.5,35.0,15.0,"['Dinner', 'Appetizer']","['World', 'Asian']","['1 tsp vegetable oil', '1 egg, beaten', '6 cu...","['Gather all ingredients.', 'Mix cabbage, bean...",['fry'],"['skillet', 'cutting board']","['10', '20 egg rolls']","{'Calories': '1268 kcal', 'Carbohydrates': '57..."
2,Spanish Tortilla,4.3,10.0,10.0,['Breakfast'],['Spanish'],"['0.25 cup olive oil', '2 potatoes, peeled', '...",['Slice edges off of potatoes so that potatoes...,['fry'],['skillet'],4,"{'Calories': '447 kcal', 'Carbohydrates': '22 ..."
3,Spicy Tarragon Yogurt Chicken,4.5,10.0,15.0,['Dinner'],['American'],"['1 bunch fresh tarragon sprigs, leaves only',...",['Set 4 tarragon sprigs aside strip leaves fr...,['grill'],"['grill', 'thermometer', 'blender']",6,"{'Calories': '316 kcal', 'Carbohydrates': '3 g..."
4,Apple Bread,4.7,15.0,45.0,['Brunch'],['American'],"['cooking spray', '3 cups all-purpose flour', ...",['Preheat the oven to 300 degrees F (150 degre...,['bake'],"['pan', 'oven', 'whisk']","['16', '2 (8x4-inch) loaves']","{'Calories': '377 kcal', 'Carbohydrates': '47 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
50508,Huge Cinnamon Rolls,5.0,30.0,25.0,['Breakfast'],['American'],"['0.25 cup warm water', '1 tablespoon white su...","['Gently mix 1/4 cup warm water, 1 tablespoon ...",['bake'],"['saucepan', 'mixer', 'pan', 'baking dish', 'o...","['6', '6 large rolls']","{'Calories': '1024 kcal', 'Carbohydrates': '14..."
50509,Spicy Salmon Marinade,NaN,10.0,10.0,['Dinner'],[],['1 (1 1/2-pound) skin-on center-cut salmon fi...,"['Cut fish into 4 portions.', 'Whisk together ...",['grill'],"['grill', 'whisk']","['4', '4 salmon fillets']","{'Calories': '314 kcal', 'Carbohydrates': '2 g..."
50510,Lemon Icebox Pie with Frozen Lemonade,4.0,5.0,0.0,['Dessert'],[],"['1 (14 ounce) can sweetened condensed milk', ...",['Mix condensed milk and lemonade concentrate ...,[],[],"['8', '1 9-inch pie']","{'Calories': '410 kcal', 'Carbohydrates': '60 ..."
50511,Easy Shrimp Chow Mein,3.0,15.0,20.0,['Dinner'],['Asian Inspired'],"['1 (6 ounce) package chow mein noodles', '0.2...",['Bring a large pot of water to a boil. Add ch...,"['simmer', 'boil']",['pot'],"['4', '4 servings']","{'Calories': '578 kcal', 'Carbohydrates': '40 ..."
50512,Garlic-Smashed Potatoes,3.5,10.0,115.0,"['Dinner', 'Side Dish']",[],"['5 pounds small red potatoes', '0.5 cup olive...",['Place potatoes into a very large pot and cov...,"['bake', 'simmer', 'boil', 'reduce']","['baking dish', 'oven', 'pot', 'whisk']","['10', '10 servings']","{'Calories': '261 kcal', 'Carbohydrates': '38 ..."

In [4]:
df['time'] = df['Preparation Time'] + df['Cooking Time']
df

,Name,Rating Value,Preparation Time,Cooking Time,Category,Cuisine,Ingredients_Raw,Instructions,Cooking Methods,Implements,Servings,Nutrition,time
0,Pineapple Glaze for Ham,4.5,10.0,5.0,['Dinner'],['American'],"['1 (15.25 ounce) can sliced pineapple, draine...","['Gather the ingredients.', 'Before baking ham...",['microwave'],['microwave'],"['14', '3 cups']","{'Calories': '93 kcal', 'Carbohydrates': '24 g...",15.0
1,Awesome Egg Rolls,4.5,35.0,15.0,"['Dinner', 'Appetizer']","['World', 'Asian']","['1 tsp vegetable oil', '1 egg, beaten', '6 cu...","['Gather all ingredients.', 'Mix cabbage, bean...",['fry'],"['skillet', 'cutting board']","['10', '20 egg rolls']","{'Calories': '1268 kcal', 'Carbohydrates': '57...",50.0
2,Spanish Tortilla,4.3,10.0,10.0,['Breakfast'],['Spanish'],"['0.25 cup olive oil', '2 potatoes, peeled', '...",['Slice edges off of potatoes so that potatoes...,['fry'],['skillet'],4,"{'Calories': '447 kcal', 'Carbohydrates': '22 ...",20.0
3,Spicy Tarragon Yogurt Chicken,4.5,10.0,15.0,['Dinner'],['American'],"['1 bunch fresh tarragon sprigs, leaves only',...",['Set 4 tarragon sprigs aside strip leaves fr...,['grill'],"['grill', 'thermometer', 'blender']",6,"{'Calories': '316 kcal', 'Carbohydrates': '3 g...",25.0
4,Apple Bread,4.7,15.0,45.0,['Brunch'],['American'],"['cooking spray', '3 cups all-purpose flour', ...",['Preheat the oven to 300 degrees F (150 degre...,['bake'],"['pan', 'oven', 'whisk']","['16', '2 (8x4-inch) loaves']","{'Calories': '377 kcal', 'Carbohydrates': '47 ...",60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50508,Huge Cinnamon Rolls,5.0,30.0,25.0,['Breakfast'],['American'],"['0.25 cup warm water', '1 tablespoon white su...","['Gently mix 1/4 cup warm water, 1 tablespoon ...",['bake'],"['saucepan', 'mixer', 'pan', 'baking dish', 'o...","['6', '6 large rolls']","{'Calories': '1024 kcal', 'Carbohydrates': '14...",55.0
50509,Spicy Salmon Marinade,NaN,10.0,10.0,['Dinner'],[],['1 (1 1/2-pound) skin-on center-cut salmon fi...,"['Cut fish into 4 portions.', 'Whisk together ...",['grill'],"['grill', 'whisk']","['4', '4 salmon fillets']","{'Calories': '314 kcal', 'Carbohydrates': '2 g...",20.0
50510,Lemon Icebox Pie with Frozen Lemonade,4.0,5.0,0.0,['Dessert'],[],"['1 (14 ounce) can sweetened condensed milk', ...",['Mix condensed milk and lemonade concentrate ...,[],[],"['8', '1 9-inch pie']","{'Calories': '410 kcal', 'Carbohydrates': '60 ...",5.0
50511,Easy Shrimp Chow Mein,3.0,15.0,20.0,['Dinner'],['Asian Inspired'],"['1 (6 ounce) package chow mein noodles', '0.2...",['Bring a large pot of water to a boil. Add ch...,"['simmer', 'boil']",['pot'],"['4', '4 servings']","{'Calories': '578 kcal', 'Carbohydrates': '40 ...",35.0
50512,Garlic-Smashed Potatoes,3.5,10.0,115.0,"['Dinner', 'Side Dish']",[],"['5 pounds small red potatoes', '0.5 cup olive...",['Place potatoes into a very large pot and cov...,"['bake', 'simmer', 'boil', 'reduce']","['baking dish', 'oven', 'pot', 'whisk']","['10', '10 servings']","{'Calories': '261 kcal', 'Carbohydrates': '38 ...",125.0

Very Short <= 10

Short 11-25

Average 26-45

Long 46-90

Very Long > 90

In [5]:
def time_class(minutes):
    if minutes <= 10:
        return "very short"
    elif minutes <= 25:
        return "short"
    elif minutes <= 45:
        return "average"
    elif minutes <= 90:
        return "long"
    else:
        return "very long"

df["time_class"] = df["time"].apply(time_class)
df = df.drop(labels=["Preparation Time", "Cooking Time"], axis=1)

In [6]:
df = df.rename(columns={"Rating Value": "rating"})
df = df.rename(columns={"Ingredients_Raw": "ingredients"})
df = df.rename(columns={"Cooking Methods": "methods"})
df = df.rename(columns={"Implements": "utensils"})

In [7]:
df["Nutrition"][105]

"{'Calories': '591 kcal', 'Carbohydrates': '71 g', 'Cholesterol': '65 mg', 'Fiber': '3 g', 'Protein': '6 g', 'Saturated Fat': '8 g', 'Sodium': '575 mg', 'Sugar': '34 g', 'Fat': '34 g', 'Unsaturated Fat': '0 g'}"

In [8]:
def safe_literal_eval(x):
    # 1. Handle NaN / None early
    if pd.isna(x):
        return None

    # 2. Ensure it's a string
    if not isinstance(x, str):
        return None

    x = x.strip()

    # 3. Attempt to fix common broken dict issue (missing closing brace)
    if x.startswith("{") and not x.endswith("}"):
        x = x + "}"

    try:
        return ast.literal_eval(x)
    except Exception as e:
        print("⚠️ Failed to parse value:")
        print(x)
        print("Error:", e)
        return None

df["Nutrition"] = df["Nutrition"].apply(safe_literal_eval)
nutrition_df = pd.json_normalize(df["Nutrition"])

nutrition_df.columns = (
    nutrition_df.columns
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

unit_mapping = {
    "calories": "kcal",
    "carbohydrates": "g",
    "cholesterol": "mg",
    "fiber": "g",
    "protein": "g",
    "saturated_fat": "g",
    "sodium": "mg",
    "sugar": "g",
    "fat": "g",
    "unsaturated_fat": "g"
}

nutrition_df.rename(columns={col: f"{col}_{unit}" for col, unit in unit_mapping.items() if col in nutrition_df.columns}, inplace=True)

df = df.drop(columns="Nutrition").join(nutrition_df)

nutrition_cols = [
    "calories_kcal",
    "carbohydrates_g",
    "cholesterol_mg",
    "fiber_g",
    "protein_g",
    "saturated_fat_g",
    "sodium_mg",
    "sugar_g",
    "fat_g",
    "unsaturated_fat_g"
]

for col in nutrition_cols:
    if df[col].dtype == object:
        df[col] = (
            df[col]
            .astype(str)
            .str.extract(r"([\d\.]+)", expand=False)
            .pipe(pd.to_numeric, errors="coerce")
        )

In [9]:
df

,Name,rating,Category,Cuisine,ingredients,Instructions,methods,utensils,Servings,time,...,calories_kcal,carbohydrates_g,cholesterol_mg,fiber_g,protein_g,saturated_fat_g,sodium_mg,sugar_g,fat_g,unsaturated_fat_g
0,Pineapple Glaze for Ham,4.5,['Dinner'],['American'],"['1 (15.25 ounce) can sliced pineapple, draine...","['Gather the ingredients.', 'Before baking ham...",['microwave'],['microwave'],"['14', '3 cups']",15.0,...,93.0,24.0,NaN,0.0,NaN,NaN,7.0,21.0,NaN,0.0
1,Awesome Egg Rolls,4.5,"['Dinner', 'Appetizer']","['World', 'Asian']","['1 tsp vegetable oil', '1 egg, beaten', '6 cu...","['Gather all ingredients.', 'Mix cabbage, bean...",['fry'],"['skillet', 'cutting board']","['10', '20 egg rolls']",50.0,...,1268.0,57.0,48.0,7.0,17.0,17.0,1050.0,3.0,110.0,0.0
2,Spanish Tortilla,4.3,['Breakfast'],['Spanish'],"['0.25 cup olive oil', '2 potatoes, peeled', '...",['Slice edges off of potatoes so that potatoes...,['fry'],['skillet'],4,20.0,...,447.0,22.0,213.0,2.0,14.0,9.0,558.0,3.0,34.0,0.0
3,Spicy Tarragon Yogurt Chicken,4.5,['Dinner'],['American'],"['1 bunch fresh tarragon sprigs, leaves only',...",['Set 4 tarragon sprigs aside strip leaves fr...,['grill'],"['grill', 'thermometer', 'blender']",6,25.0,...,316.0,3.0,152.0,0.0,57.0,2.0,1281.0,2.0,7.0,0.0
4,Apple Bread,4.7,['Brunch'],['American'],"['cooking spray', '3 cups all-purpose flour', ...",['Preheat the oven to 300 degrees F (150 degre...,['bake'],"['pan', 'oven', 'whisk']","['16', '2 (8x4-inch) loaves']",60.0,...,377.0,47.0,35.0,2.0,5.0,3.0,238.0,28.0,20.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50508,Huge Cinnamon Rolls,5.0,['Breakfast'],['American'],"['0.25 cup warm water', '1 tablespoon white su...","['Gently mix 1/4 cup warm water, 1 tablespoon ...",['bake'],"['saucepan', 'mixer', 'pan', 'baking dish', 'o...","['6', '6 large rolls']",55.0,...,1024.0,149.0,33.0,5.0,11.0,8.0,655.0,89.0,45.0,0.0
50509,Spicy Salmon Marinade,NaN,['Dinner'],[],['1 (1 1/2-pound) skin-on center-cut salmon fi...,"['Cut fish into 4 portions.', 'Whisk together ...",['grill'],"['grill', 'whisk']","['4', '4 salmon fillets']",20.0,...,314.0,2.0,75.0,0.0,36.0,3.0,394.0,1.0,13.0,0.0
50510,Lemon Icebox Pie with Frozen Lemonade,4.0,['Dessert'],[],"['1 (14 ounce) can sweetened condensed milk', ...",['Mix condensed milk and lemonade concentrate ...,[],[],"['8', '1 9-inch pie']",5.0,...,410.0,60.0,17.0,1.0,5.0,9.0,234.0,48.0,16.0,0.0
50511,Easy Shrimp Chow Mein,3.0,['Dinner'],['Asian Inspired'],"['1 (6 ounce) package chow mein noodles', '0.2...",['Bring a large pot of water to a boil. Add ch...,"['simmer', 'boil']",['pot'],"['4', '4 servings']",35.0,...,578.0,40.0,346.0,6.0,48.0,5.0,1625.0,6.0,25.0,0.0
50512,Garlic-Smashed Potatoes,3.5,"['Dinner', 'Side Dish']",[],"['5 pounds small red potatoes', '0.5 cup olive...",['Place potatoes into a very large pot and cov...,"['bake', 'simmer', 'boil', 'reduce']","['baking dish', 'oven', 'pot', 'whisk']","['10', '10 servings']",125.0,...,261.0,38.0,NaN,4.0,5.0,2.0,364.0,2.0,11.0,0.0

In [ ]:
print(df.columns.tolist())

['Name', 'rating', 'Category', 'Cuisine', 'ingredients', 'Instructions', 'methods', 'utensils', 'Servings', 'time', 'time_class', 'calories_kcal', 'carbohydrates_g', 'cholesterol_mg', 'fiber_g', 'protein_g', 'saturated_fat_g', 'sodium_mg', 'sugar_g', 'fat_g', 'unsaturated_fat_g']

In [11]:
df = df.rename(columns={"Name": "name"})
df = df.rename(columns={"Category": "category"})
df = df.rename(columns={"Cuisine": "cuisine"})
df = df.rename(columns={"Instructions": "instructions"})
df = df.rename(columns={"Servings": "servings"})

df

,name,rating,category,cuisine,ingredients,instructions,methods,utensils,servings,time,...,calories_kcal,carbohydrates_g,cholesterol_mg,fiber_g,protein_g,saturated_fat_g,sodium_mg,sugar_g,fat_g,unsaturated_fat_g
0,Pineapple Glaze for Ham,4.5,['Dinner'],['American'],"['1 (15.25 ounce) can sliced pineapple, draine...","['Gather the ingredients.', 'Before baking ham...",['microwave'],['microwave'],"['14', '3 cups']",15.0,...,93.0,24.0,NaN,0.0,NaN,NaN,7.0,21.0,NaN,0.0
1,Awesome Egg Rolls,4.5,"['Dinner', 'Appetizer']","['World', 'Asian']","['1 tsp vegetable oil', '1 egg, beaten', '6 cu...","['Gather all ingredients.', 'Mix cabbage, bean...",['fry'],"['skillet', 'cutting board']","['10', '20 egg rolls']",50.0,...,1268.0,57.0,48.0,7.0,17.0,17.0,1050.0,3.0,110.0,0.0
2,Spanish Tortilla,4.3,['Breakfast'],['Spanish'],"['0.25 cup olive oil', '2 potatoes, peeled', '...",['Slice edges off of potatoes so that potatoes...,['fry'],['skillet'],4,20.0,...,447.0,22.0,213.0,2.0,14.0,9.0,558.0,3.0,34.0,0.0
3,Spicy Tarragon Yogurt Chicken,4.5,['Dinner'],['American'],"['1 bunch fresh tarragon sprigs, leaves only',...",['Set 4 tarragon sprigs aside strip leaves fr...,['grill'],"['grill', 'thermometer', 'blender']",6,25.0,...,316.0,3.0,152.0,0.0,57.0,2.0,1281.0,2.0,7.0,0.0
4,Apple Bread,4.7,['Brunch'],['American'],"['cooking spray', '3 cups all-purpose flour', ...",['Preheat the oven to 300 degrees F (150 degre...,['bake'],"['pan', 'oven', 'whisk']","['16', '2 (8x4-inch) loaves']",60.0,...,377.0,47.0,35.0,2.0,5.0,3.0,238.0,28.0,20.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50508,Huge Cinnamon Rolls,5.0,['Breakfast'],['American'],"['0.25 cup warm water', '1 tablespoon white su...","['Gently mix 1/4 cup warm water, 1 tablespoon ...",['bake'],"['saucepan', 'mixer', 'pan', 'baking dish', 'o...","['6', '6 large rolls']",55.0,...,1024.0,149.0,33.0,5.0,11.0,8.0,655.0,89.0,45.0,0.0
50509,Spicy Salmon Marinade,NaN,['Dinner'],[],['1 (1 1/2-pound) skin-on center-cut salmon fi...,"['Cut fish into 4 portions.', 'Whisk together ...",['grill'],"['grill', 'whisk']","['4', '4 salmon fillets']",20.0,...,314.0,2.0,75.0,0.0,36.0,3.0,394.0,1.0,13.0,0.0
50510,Lemon Icebox Pie with Frozen Lemonade,4.0,['Dessert'],[],"['1 (14 ounce) can sweetened condensed milk', ...",['Mix condensed milk and lemonade concentrate ...,[],[],"['8', '1 9-inch pie']",5.0,...,410.0,60.0,17.0,1.0,5.0,9.0,234.0,48.0,16.0,0.0
50511,Easy Shrimp Chow Mein,3.0,['Dinner'],['Asian Inspired'],"['1 (6 ounce) package chow mein noodles', '0.2...",['Bring a large pot of water to a boil. Add ch...,"['simmer', 'boil']",['pot'],"['4', '4 servings']",35.0,...,578.0,40.0,346.0,6.0,48.0,5.0,1625.0,6.0,25.0,0.0
50512,Garlic-Smashed Potatoes,3.5,"['Dinner', 'Side Dish']",[],"['5 pounds small red potatoes', '0.5 cup olive...",['Place potatoes into a very large pot and cov...,"['bake', 'simmer', 'boil', 'reduce']","['baking dish', 'oven', 'pot', 'whisk']","['10', '10 servings']",125.0,...,261.0,38.0,NaN,4.0,5.0,2.0,364.0,2.0,11.0,0.0

In [12]:
df.to_csv('cleaned.csv', index=False)